language: cpp

compiler:
  - gcc

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required

before_install:
    - sudo apt install openjdk-11-jdk
                       libx11-dev 
                       libxext-dev 
                       libxrender-dev 
                       libxtst-dev 
                       libxt-dev
                       libcups2-dev
                       libasound2-dev
                       libasound2-dev
script:
  - bash configure
        --with-version-build="1"
        --with-version-pre=''
        --with-version-opt=''
        --enable-unlimited-crypto=yes
        --disable-warnings-as-errors
        --disable-hotspot-gtest
        --with-debug-level=release
        --with-stdc++lib=dynamic
        --with-zlib=system
        --with-lcms=system
        --with-libpng=system
        --with-libjpeg=system
        --with-version-pre=''
        --with-version-opt=''
        --with-jvm-features=zgc
        --with-giflib=system

  - make images
