language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt install openjdk-11-jdk
    - sudo apt-get install libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
    - sudo apt-get install libcups2-dev
script:
  - bash ./configure && make images
