language: cpp

compiler:
  - gcc

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required

# install:
#  - apt-get install default-jdk
#  - sudo add-apt-repository -y ppa:openjdk-r/ppa
#  - sudo apt-get update -q
#  - sudo apt-get install openjdk-11-jdk
script:
  - bash configure
        --with-boot-jdk=/usr/lib/jvm/java-11-openjdk-amd64/
        --with-version-build=''
        --with-version-pre=''
        --with-version-opt=''
        --enable-unlimited-crypto=yes
        --disable-warnings-as-errors
        --disable-hotspot-gtest
        --with-debug-level=release
        --with-stdc++lib=dynamic
        --with-zlib=system
        --with-lcms=system
        --with-libpng=system
        --with-libjpeg=system
        --with-version-pre=''
        --with-version-opt=''
        --with-jvm-features=zgc
        --with-giflib=system

  - make images
