language: cpp

compiler:
  - gcc

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required

install:
  - (cd /opt; curl -LO https://github.com/ojdkbuild/contrib_jdk10u-ci/releases/download/jdk-10.0.2%2B13/jdk-10.0.2-ojdkbuild-linux-x64.zip)
  - (cd /opt; unzip -q jdk-10.0.2-ojdkbuild-linux-x64.zip)
  - (cd /opt; mv jdk-10.0.2-ojdkbuild-linux-x64 bootjdk)
   
#  - apt-get install default-jdk
#  - sudo add-apt-repository -y ppa:openjdk-r/ppa
#  - sudo apt-get update -q
#  - sudo apt-get install openjdk-11-jdk
script:
  - bash -c "bash ./configure
        --enable-unlimited-crypto=yes
        --disable-warnings-as-errors
        --disable-hotspot-gtest
        --with-native-debug-symbols=${OJDK_WITH_NATIVE_DEBUG_SYMBOLS} 
        --with-debug-level=${OJDK_WITH_DEBUG_LEVEL}
        --with-stdc++lib=dynamic
        --with-zlib=bundled
        --with-boot-jdk=/opt/bootjdk
        --with-version-pre=dcevmbuild
        --with-version-build=''
        --with-version-opt=''
        --with-log=info"
  - make images
