language: cpp
before_install:
    - sudo apt-get update -qq
    - sudo apt install openjdk-11-jdk
                       libx11-dev 
                       libxext-dev 
                       libxrender-dev 
                       libxtst-dev 
                       libxt-dev
                       libcups2-dev
                       libasound2-dev
                       libasound2-dev
script:
  - bash configure
        --enable-unlimited-crypto=yes
        --disable-warnings-as-errors
        --disable-hotspot-gtest
        --with-debug-level=release
        --with-stdc++lib=static
        --with-zlib=bundled
        --with-version-pre=''
        --with-version-opt=''
  - make images
